# This file is managed by 'repo_helper'. Don't edit it directly.
# Read the Docs configuration file
---

# Required
version: 2

sphinx:
  builder: html
  configuration: doc-source/conf.py

python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - requirements: doc-source/requirements.txt
